name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v -o trade -ldflags "-s -w" ./cmd/app/main.go
    
    - name: structure data
      run: |
        mkdir -p .debpkg/usr/bin
        cp ./trade .debpkg/usr/bin/trade
        chmod +x .debpkg/usr/bin/trade
    - name: Build debian package
      uses: albeego/deb-builder-action@master
      with:
        execution_path: build
        package_name: trade
        target_architecture: amd64
