name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v -o trade -ldflags "-s -w" ./cmd/app/main.go

    - name: Build debian package
      run: |
        apt update && apt install --no-install-recommends dpkg-dev -y

        VERSION="${GITHUB_REF##*/}"
        BUILD_BASE="/tmp/build"
        BUILD_DIR="${BUILD_BASE}/trade-${VERSION}"

        echo "Latest version: $VERSION"
        mkdir -p "${BUILD_DIR}/debian"

        git tag --list "*.*.*" --sort=-authordate --sort=-v:refname --format "trade (%(refname:lstrip=-1)) UNRELEASED; urgency=medium%0a%0a  * %(subject)%0a%0a -- %(authorname) %(authoremail)  %(authordate:rfc2822)" > "${BUILD_DIR}/debian/changelog"

        cp -r asset trade "${BUILD_DIR}"

        cd "${BUILD_DIR}"

        dpkg-buildpackage

        cd -

        cp "${BUILD_BASE}/"*.deb .
