name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: "ubuntu:latest"
    steps:
    - name: Install git
      run: apt-get update && apt-get -y install git

    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Build
      run: go build -o trade -trimpath -ldflags "-s -w" ./cmd/app/main.go

    - name: Build debian package
      run: |
        apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends git dpkg-dev dh-make -y

        BUILD_BASE="/tmp/build"
        mkdir -p "${BUILD_BASE}"

        git tag --list "*.*.*" --sort=-authordate --sort=-v:refname --format "trade (%(refname:lstrip=-1)) UNRELEASED; urgency=medium%0a%0a  * %(subject)%0a%0a -- %(*authorname) %(*authoremail)  %(*authordate:rfc2822)" > "${BUILD_BASE}/changelog"

        cat "${BUILD_BASE}/changelog"

        VERSION="$(dpkg-parsechangelog --file "${BUILD_BASE}/changelog" --show-field VERSION)"
        BUILD_DIR="${BUILD_BASE}/trade-${VERSION}"
        mkdir -p "${BUILD_DIR}/debian"

        echo "Latest version: $VERSION"

        mv "${BUILD_BASE}/changelog" "${BUILD_DIR}/debian/"
        cp -r debian assets trade "${BUILD_DIR}"

        cd "${BUILD_DIR}"

        dpkg-buildpackage

        cd -

        cp "${BUILD_BASE}/"*.deb .
