name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5

    - name: Build
      run: go build -v -o trade -trimpat -ldflags "-s -w" ./cmd/app/main.go

    - name: Build debian package
      run: |
        sudo apt-get update && sudo apt-get install --no-install-recommends dpkg-dev -y

        BUILD_BASE="/tmp/build"
        mkdir -p "${BUILD_BASE}"

        git tag --list "*.*.*" --sort=-authordate --sort=-v:refname --format "trade (%(refname:lstrip=-1)) UNRELEASED; urgency=medium%0a%0a  * %(subject)%0a%0a -- %(authorname) %(authoremail)  %(authordate:rfc2822)" > "${BUILD_BASE}/changelog"

        VERSION="$(dpkg-parsechangelog --file "${BUILD_BASE}/changelog" --show-field VERSION)"
        BUILD_DIR="${BUILD_BASE}/trade-${VERSION}"
        mkdir -p "${BUILD_DIR}/debian"

        echo "Latest version: $VERSION"

        mv "${BUILD_BASE}/changelog" "${BUILD_DIR}/debian/"
        cp -r debian asset trade "${BUILD_DIR}"

        cd "${BUILD_DIR}"

        dpkg-buildpackage

        cd -

        cp "${BUILD_BASE}/"*.deb .
