name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: debian-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v -o trade -ldflags "-s -w" ./cmd/app/main.go
    
    - name: structure data
      run: |
        mkdir -p .debpkg/usr/bin
        cp ./trade .debpkg/usr/bin/trade
        chmod +x .debpkg/usr/bin/trade
    - uses: jiro4989/build-deb-action@v2
      with:
        package: trade
        package_root: .debpkg
        maintainer: kaedwen
        version: ${{ github.ref }} # refs/tags/v*.*.*
        arch: 'amd64'
        depends: 'libc6'
        desc: 'Comdirect trade api package.'
